marks=[]
m1= input("enter the number here")
marks.append(m1)
m2= input("enter the number here")
marks.append(m2)
m3= input("enter the number here")
marks.append(m3)
m4= input("enter the number here")
marks.append(m4)
m5= input("enter the number here")
marks.append(m5)
m6= input("enter the number here ")
marks.sort()
print (marks)